language: go
sudo: false
install:
  - mkdir -p vendor/github.com/go-redis
  - git clone https://github.com/go-redis/redis vendor/github.com/go-redis/redis
  - (cd vendor/github.com/go-redis/redis && git checkout master)
  - go get -u -t ./...
services:
  - redis-server
go:
  - 1.6.4
  - 1.7.5
  - 1.8
